
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    test.App\Repository\ArchdeaconryRepository: '@App\Repository\ArchdeaconryRepository'
    test.App\Repository\ArchiveRepository: '@App\Repository\ArchiveRepository'
    test.App\Repository\BookRepository: '@App\Repository\BookRepository'
    test.App\Repository\CountyRepository: '@App\Repository\CountyRepository'
    test.App\Repository\DioceseRepository: '@App\Repository\DioceseRepository'
    test.App\Repository\FormatRepository: '@App\Repository\FormatRepository'
    test.App\Repository\NationRepository: '@App\Repository\NationRepository'
    test.App\Repository\ParishRepository: '@App\Repository\ParishRepository'
    test.App\Repository\ProvinceRepository: '@App\Repository\ProvinceRepository'
    test.App\Repository\SourceCategoryRepository: '@App\Repository\SourceCategoryRepository'
    test.App\Repository\SourceRepository: '@App\Repository\SourceRepository'
    test.App\Repository\TownRepository: '@App\Repository\TownRepository'
    test.App\Repository\TransactionCategoryRepository: '@App\Repository\TransactionCategoryRepository'
    test.App\Repository\TransactionRepository: '@App\Repository\TransactionRepository'
    test.App\Repository\HoldingRepository: '@App\Repository\HoldingRepository'
    test.App\Repository\InventoryRepository: '@App\Repository\InventoryRepository'
    test.App\Repository\InjunctionRepository: '@App\Repository\InjunctionRepository'
